## YAML Template.
rsvplist.settings:
  type: config_object
  label: 'RSVP List content type settings'
  mapping:
    allowed_types:
      type: sequence
      label: 'Content type RSVP form can display on'
      sequence: 
        type: string
        label: 'Content type'  
